### ISSUE TITLE
Mouse Tracking is Buggy under Windows 10

### ISSUE THREAD

**Issue by everyfan** [barotto/IBMulator#15]
It does not track the external mouse properly, even when I turn off my laptop's trackpad.

**Comment by barotto** [comment]
Can you be more specific? Does it work but it's laggy or is it not functional at all? What OS are you using?

**Comment by barotto** [comment]
Another user told me about mouse getting stuck under Windows 10. It seems like a platform bug.

**Comment by barotto** [comment]
It's a SDL bug: https://discourse.libsdl.org/t/win10-fall-creators-update-breaks-mouse-warping/23526

**Comment by barotto** [comment]
This is not an IBMulator's bug, rather a SDL's bug. I'll do a binary release with the most recent SDL version.

**Comment by barotto** [comment]
This issue has been addressed with commit 6f09e0b.
