### ISSUE TITLE
#GP fault in Pinball Illusions

### ISSUE THREAD

**Issue by barotto** [barotto/IBMulator#32]
A general protection fault happens during the Pinball Illusions'  intro.

![screenshot_0042](https://user-images.githubusercontent.com/5670600/40283051-a80228aa-5c78-11e8-9336-f28b6ef58c0f.png)

note to self: hdd-47-800_16_62-DOS622-VGA-test.img in dir illusion

**Comment by superfury** [comment]
This is what I'm getting in UniPCemu with the current commit:

![547](https://user-images.githubusercontent.com/1992026/41097817-9888e384-6a59-11e8-8916-1c8854190ec5.jpg)

It's some MOV instruction, apparently.

**Comment by superfury** [comment]
I've made a big log of the problem that's occurring:
https://www.dropbox.com/s/7rzmxql2pw8ufo4/debugger_pinballillusions_crash.7z?dl=0

I see some POP ES rights somewhere before the invalid MOVSW, which pops an code descriptor value into ES that's causing said fault. That ones overwriting it with the same value it contained already. Looking somewhere further up, another value was in ES, but it was overwritten to said code segment for some odd reason(before the RETFD).

**Comment by superfury** [comment]
Looking at the log, I see:
The line starting with 05:59:57:26.08992 is the fault that's triggered by the MOVSW instruction to the invalid ES(=Code segment) descriptor. Searching up for ES not being 0014, I find:

`000c:00000eb4 07 pop es	RAM(r):00028003=00( ); Physical(r):00028003=00( ); Paged(r):00028003=00( ); RAM(r):00028002=02(); Physical(r):00028002=02(); Paged(r):00028002=02(); RAM(r):00028001=70(p); Physical(r):00028001=70(p); Paged(r):00028001=70(p); RAM(r):00028000=23(#); Physical(r):00028000=23(#); Paged(r):00028000=23(#); RAM(r):0002706B=00( ); Physical(r):0002706B=00( ); Paged(r):0002706B=00( ); RAM(r):0002706A=01(); Physical(r):0002706A=01(); Paged(r):0002706A=01(); RAM(r):00027069=A0(?); Physical(r):00027069=A0(?); Paged(r):00027069=A0(?); RAM(r):00027068=67(g); Physical(r):00027068=67(g); Paged(r):00027068=67(g)
Registers:
EAX: 000000d1 EBX: 000032f8 ECX: 00000000 EDX: 00000001
ESP: 00001fba EBP: 2aac0000 ESI: 00001822 EDI: 00000c11
CS: 000c DS: 0004 ES: 0034 FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00000eb4 EFLAGS: 00003213
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsz0A0p1C 
`

So it's popping the wrong ES value from a stack?

**Comment by superfury** [comment]
Right before it it's a loop that reads and substracts 8-bit numbers from an array in memory?

`	RAM(r):00028003=00( ); Physical(r):00028003=00( ); Paged(r):00028003=00( ); RAM(r):00028002=02(); Physical(r):00028002=02(); Paged(r):00028002=02(); RAM(r):00028001=70(p); Physical(r):00028001=70(p); Paged(r):00028001=70(p); RAM(r):00028000=23(#); Physical(r):00028000=23(#); Paged(r):00028000=23(#); RAM(r):00027427=00( ); Physical(r):00027427=00( ); Paged(r):00027427=00( ); RAM(r):00027426=17(); Physical(r):00027426=17(); Paged(r):00027426=17(); RAM(r):00027425=20( ); Physical(r):00027425=20( ); Paged(r):00027425=20( ); RAM(r):00027424=67(g); Physical(r):00027424=67(g); Paged(r):00027424=67(g); RAM(p):00172A9A=B9(?); Physical(p):00172A9A=B9(?); Paged(p):00172A9A=B9(?); RAM(p):00172A9B=59(Y); Physical(p):00172A9B=59(Y); Paged(p):00172A9B=59(Y); RAM(p):00172A9C=03(); Physical(p):00172A9C=03(); Paged(p):00172A9C=03(); RAM(p):00172A9D=00( ); Physical(p):00172A9D=00( ); Paged(p):00172A9D=00( )
	RAM(p):00172A9E=00( ); Physical(p):00172A9E=00( ); Paged(p):00172A9E=00( ); RAM(p):00172A9F=BE(?); Physical(p):00172A9F=BE(?); Paged(p):00172A9F=BE(?); RAM(p):00172AA0=20( ); Physical(p):00172AA0=20( ); Paged(p):00172AA0=20( ); RAM(p):00172AA1=4F(O); Physical(p):00172AA1=4F(O); Paged(p):00172AA1=4F(O)
0014:00004eda B9 59 03 00 00 mov ecx,00000359
Registers:
EAX: 00000810 EBX: 000072a4 ECX: 00000008 EDX: 000003c5
ESP: 00001ff2 EBP: 00000000 ESI: 0000031a EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004eda EFLAGS: 00003246
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsZ0a0P1c 
	RAM(p):00172AA2=00( ); Physical(p):00172AA2=00( ); Paged(p):00172AA2=00( ); RAM(p):00172AA3=00( ); Physical(p):00172AA3=00( ); Paged(p):00172AA3=00( ); RAM(p):00172AA4=8B(?); Physical(p):00172AA4=8B(?); Paged(p):00172AA4=8B(?); RAM(p):00172AA5=1D(); Physical(p):00172AA5=1D(); Paged(p):00172AA5=1D()
0014:00004edf BE 20 4F 00 00 mov esi,00004f20	RAM(p):00172AA6=E7(?); Physical(p):00172AA6=E7(?); Paged(p):00172AA6=E7(?); RAM(p):00172AA7=1F(); Physical(p):00172AA7=1F(); Paged(p):00172AA7=1F(); RAM(p):00172AA8=00( ); Physical(p):00172AA8=00( ); Paged(p):00172AA8=00( ); RAM(p):00172AA9=00( ); Physical(p):00172AA9=00( ); Paged(p):00172AA9=00( )
Registers:
EAX: 00000810 EBX: 000072a4 ECX: 00000359 EDX: 000003c5
ESP: 00001ff2 EBP: 00000000 ESI: 0000031a EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004edf EFLAGS: 00003246
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsZ0a0P1c 
	RAM(p):00172AAA=E8(?); Physical(p):00172AAA=E8(?); Paged(p):00172AAA=E8(?); RAM(p):00172AAB=DF(?); Physical(p):00172AAB=DF(?); Paged(p):00172AAB=DF(?); RAM(p):00172AAC=FC(?); Physical(p):00172AAC=FC(?); Paged(p):00172AAC=FC(?); RAM(p):00172AAD=FF(?); Physical(p):00172AAD=FF(?); Paged(p):00172AAD=FF(?)
	RAM(r):00028003=00( ); Physical(r):00028003=00( ); Paged(r):00028003=00( ); RAM(r):00028002=02(); Physical(r):00028002=02(); Paged(r):00028002=02(); RAM(r):00028001=70(p); Physical(r):00028001=70(p); Paged(r):00028001=70(p); RAM(r):00028000=23(#); Physical(r):00028000=23(#); Paged(r):00028000=23(#); RAM(r):0002741B=00( ); Physical(r):0002741B=00( ); Paged(r):0002741B=00( ); RAM(r):0002741A=17(); Physical(r):0002741A=17(); Paged(r):0002741A=17(); RAM(r):00027419=50(P); Physical(r):00027419=50(P); Paged(r):00027419=50(P); RAM(r):00027418=67(g); Physical(r):00027418=67(g); Paged(r):00027418=67(g); RAM(r):00175BA7=02(); Physical(r):00175BA7=02(); Paged(r):00175BA7=02()
	RAM(r):00175BA8=9C(?); Physical(r):00175BA8=9C(?); Paged(r):00175BA8=9C(?); RAM(r):00175BA9=01(); Physical(r):00175BA9=01(); Paged(r):00175BA9=01(); RAM(r):00175BAA=00( ); Physical(r):00175BAA=00( ); Paged(r):00175BAA=00( )
0014:00004ee4 8B 1D E7 1F 00 00 mov ebx,dword ds:[00001fe7]	RAM(p):00172AAE=FF(?); Physical(p):00172AAE=FF(?); Paged(p):00172AAE=FF(?); RAM(p):00172AAF=B9(?); Physical(p):00172AAF=B9(?); Paged(p):00172AAF=B9(?); RAM(p):00172AB0=FF(?); Physical(p):00172AB0=FF(?); Paged(p):00172AB0=FF(?); RAM(p):00172AB1=3A(:); Physical(p):00172AB1=3A(:); Paged(p):00172AB1=3A(:)
Registers:
EAX: 00000810 EBX: 000072a4 ECX: 00000359 EDX: 000003c5
ESP: 00001ff2 EBP: 00000000 ESI: 00004f20 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004ee4 EFLAGS: 00003246
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsZ0a0P1c 
	Paged(w):0001F25E=EF(?); Paged(w):0001F25F=4E(N); Physical(w):0001F25E=EF(?); RAM(w):0001F25E=EF(?); Physical(w):0001F25F=4E(N); RAM(w):0001F25F=4E(N)
	Paged(w):0001F260=00( ); Physical(w):0001F260=00( ); RAM(w):0001F260=00( ); Paged(w):0001F261=00( ); Physical(w):0001F261=00( ); RAM(w):0001F261=00( )
0014:00004eea E8 DF FC FF FF calld 00004bce	RAM(p):0017278E=33(3); Physical(p):0017278E=33(3); Paged(p):0017278E=33(3); RAM(p):0017278F=C0(?); Physical(p):0017278F=C0(?); Paged(p):0017278F=C0(?); RAM(p):00172790=AC(?); Physical(p):00172790=AC(?); Paged(p):00172790=AC(?); RAM(p):00172791=2B(+); Physical(p):00172791=2B(+); Paged(p):00172791=2B(+)
Registers:
EAX: 00000810 EBX: 00019c02 ECX: 00000359 EDX: 000003c5
ESP: 00001ff2 EBP: 00000000 ESI: 00004f20 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004eea EFLAGS: 00003246
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsZ0a0P1c 
	RAM(p):00172792=D8(?); Physical(p):00172792=D8(?); Paged(p):00172792=D8(?); RAM(p):00172793=E2(?); Physical(p):00172793=E2(?); Paged(p):00172793=E2(?); RAM(p):00172794=FB(?); Physical(p):00172794=FB(?); Paged(p):00172794=FB(?); RAM(p):00172795=FF(?); Physical(p):00172795=FF(?); Paged(p):00172795=FF(?)
	RAM(p):00172796=E3(?); Physical(p):00172796=E3(?); Paged(p):00172796=E3(?); RAM(p):00172797=66(f); Physical(p):00172797=66(f); Paged(p):00172797=66(f); RAM(p):00172798=8C(?); Physical(p):00172798=8C(?); Paged(p):00172798=8C(?); RAM(p):00172799=D8(?); Physical(p):00172799=D8(?); Paged(p):00172799=D8(?)
	RAM(p):0017279A=8E(?); Physical(p):0017279A=8E(?); Paged(p):0017279A=8E(?); RAM(p):0017279B=C0(?); Physical(p):0017279B=C0(?); Paged(p):0017279B=C0(?); RAM(p):0017279C=66(f); Physical(p):0017279C=66(f); Paged(p):0017279C=66(f); RAM(p):0017279D=A3(?); Physical(p):0017279D=A3(?); Paged(p):0017279D=A3(?)
0014:00004bce 33 C0 xor eax,eax
Registers:
EAX: 00000810 EBX: 00019c02 ECX: 00000359 EDX: 000003c5
ESP: 00001fee EBP: 00000000 ESI: 00004f20 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004bce EFLAGS: 00003246
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsZ0a0P1c 
	RAM(r):00172AE0=80(?); Physical(r):00172AE0=80(?); Paged(r):00172AE0=80(?)
0014:00004bd0 AC lodsb
Registers:
EAX: 00000000 EBX: 00019c02 ECX: 00000359 EDX: 000003c5
ESP: 00001fee EBP: 00000000 ESI: 00004f20 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004bd0 EFLAGS: 00003246
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsZ0a0P1c 
0014:00004bd1 2B D8 sub ebx,eax	RAM(p):0017279E=FD(?); Physical(p):0017279E=FD(?); Paged(p):0017279E=FD(?); RAM(p):0017279F=11(); Physical(p):0017279F=11(); Paged(p):0017279F=11(); RAM(p):001727A0=00( ); Physical(p):001727A0=00( ); Paged(p):001727A0=00( ); RAM(p):001727A1=00( ); Physical(p):001727A1=00( ); Paged(p):001727A1=00( )
Registers:
EAX: 00000080 EBX: 00019c02 ECX: 00000359 EDX: 000003c5
ESP: 00001fee EBP: 00000000 ESI: 00004f21 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004bd1 EFLAGS: 00003246
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsZ0a0P1c 
0014:00004bd3 E2 FB loop 00004bd0	RAM(p):00172790=AC(?); Physical(p):00172790=AC(?); Paged(p):00172790=AC(?); RAM(p):00172791=2B(+); Physical(p):00172791=2B(+); Paged(p):00172791=2B(+); RAM(p):00172792=D8(?); Physical(p):00172792=D8(?); Paged(p):00172792=D8(?); RAM(p):00172793=E2(?); Physical(p):00172793=E2(?); Paged(p):00172793=E2(?)
Registers:
EAX: 00000080 EBX: 00019b82 ECX: 00000359 EDX: 000003c5
ESP: 00001fee EBP: 00000000 ESI: 00004f21 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004bd3 EFLAGS: 00003206
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsz0a0P1c 
	RAM(p):00172794=FB(?); Physical(p):00172794=FB(?); Paged(p):00172794=FB(?); RAM(p):00172795=FF(?); Physical(p):00172795=FF(?); Paged(p):00172795=FF(?); RAM(p):00172796=E3(?); Physical(p):00172796=E3(?); Paged(p):00172796=E3(?); RAM(p):00172797=66(f); Physical(p):00172797=66(f); Paged(p):00172797=66(f)
	RAM(p):00172798=8C(?); Physical(p):00172798=8C(?); Paged(p):00172798=8C(?); RAM(p):00172799=D8(?); Physical(p):00172799=D8(?); Paged(p):00172799=D8(?); RAM(p):0017279A=8E(?); Physical(p):0017279A=8E(?); Paged(p):0017279A=8E(?); RAM(p):0017279B=C0(?); Physical(p):0017279B=C0(?); Paged(p):0017279B=C0(?)
	RAM(r):00172AE1=3D(=); Physical(r):00172AE1=3D(=); Paged(r):00172AE1=3D(=)
0014:00004bd0 AC lodsb	RAM(p):0017279C=66(f); Physical(p):0017279C=66(f); Paged(p):0017279C=66(f); RAM(p):0017279D=A3(?); Physical(p):0017279D=A3(?); Paged(p):0017279D=A3(?); RAM(p):0017279E=FD(?); Physical(p):0017279E=FD(?); Paged(p):0017279E=FD(?); RAM(p):0017279F=11(); Physical(p):0017279F=11(); Paged(p):0017279F=11()
Registers:
EAX: 00000080 EBX: 00019b82 ECX: 00000358 EDX: 000003c5
ESP: 00001fee EBP: 00000000 ESI: 00004f21 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004bd0 EFLAGS: 00003206
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsz0a0P1c 
0014:00004bd1 2B D8 sub ebx,eax
Registers:
EAX: 0000003d EBX: 00019b82 ECX: 00000358 EDX: 000003c5
ESP: 00001fee EBP: 00000000 ESI: 00004f22 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004bd1 EFLAGS: 00003206
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsz0a0P1c 
0014:00004bd3 E2 FB loop 00004bd0	RAM(p):00172790=AC(?); Physical(p):00172790=AC(?); Paged(p):00172790=AC(?); RAM(p):00172791=2B(+); Physical(p):00172791=2B(+); Paged(p):00172791=2B(+); RAM(p):00172792=D8(?); Physical(p):00172792=D8(?); Paged(p):00172792=D8(?); RAM(p):00172793=E2(?); Physical(p):00172793=E2(?); Paged(p):00172793=E2(?)
Registers:
EAX: 0000003d EBX: 00019b45 ECX: 00000358 EDX: 000003c5
ESP: 00001fee EBP: 00000000 ESI: 00004f22 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004bd3 EFLAGS: 00003212
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsz0A0p1c 
	RAM(p):00172794=FB(?); Physical(p):00172794=FB(?); Paged(p):00172794=FB(?); RAM(p):00172795=FF(?); Physical(p):00172795=FF(?); Paged(p):00172795=FF(?); RAM(p):00172796=E3(?); Physical(p):00172796=E3(?); Paged(p):00172796=E3(?); RAM(p):00172797=66(f); Physical(p):00172797=66(f); Paged(p):00172797=66(f)
	RAM(p):00172798=8C(?); Physical(p):00172798=8C(?); Paged(p):00172798=8C(?); RAM(p):00172799=D8(?); Physical(p):00172799=D8(?); Paged(p):00172799=D8(?); RAM(p):0017279A=8E(?); Physical(p):0017279A=8E(?); Paged(p):0017279A=8E(?); RAM(p):0017279B=C0(?); Physical(p):0017279B=C0(?); Paged(p):0017279B=C0(?)
	RAM(r):00172AE2=EA(?); Physical(r):00172AE2=EA(?); Paged(r):00172AE2=EA(?)
`

The eventual remainder of EBX is used as a JMP point(that GRP5 opcode) to jump to the code that creates the invalid ES segment selector by loading CS into ES(through AX)?

**Comment by superfury** [comment]
This seems to be the code that determines the starting point for determining the EBX to jump to said code:
`0014:00004ee4 8B 1D E7 1F 00 00 mov ebx,dword ds:[00001fe7]	RAM(p):00172AAE=FF(?); Physical(p):00172AAE=FF(?); Paged(p):00172AAE=FF(?); RAM(p):00172AAF=B9(?); Physical(p):00172AAF=B9(?); Paged(p):00172AAF=B9(?); RAM(p):00172AB0=FF(?); Physical(p):00172AB0=FF(?); Paged(p):00172AB0=FF(?); RAM(p):00172AB1=3A(:); Physical(p):00172AB1=3A(:); Paged(p):00172AB1=3A(:)
Registers:
EAX: 00000810 EBX: 000072a4 ECX: 00000359 EDX: 000003c5
ESP: 00001ff2 EBP: 00000000 ESI: 00004f20 EDI: 000072a4
CS: 0014 DS: 001c ES: 001c FS: 0018 GS: 0080 SS: 0058 TR: 0070 LDTR: 0060
EIP: 00004ee4 EFLAGS: 00003246
CR0: 8000fff1 CR1: 00000000 CR2: 00000000 CR3: 00028000
DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
DR6: 00000000 DR7: 00000000
GDTR: 000000019f2001ff IDTR: 00000001a15007ff
FLAGSINFO: 00000000000000vr0n11odItsZ0a0P1c `

Are those reads even correct? ....

**Comment by superfury** [comment]
After the latest fix in using top-down segments and segmentation limits, I now see the BIU faulting on a invalid EIP address, before the earlier fault at C31 occurs?

**Comment by superfury** [comment]
Any idea what those numbers in white at the bottom mean? 000031E9 in my latest case?

**Comment by superfury** [comment]
Good news: with the more recent bugfixes(just now tested), the Pinball Illusions movie no longer hangs! :D

Also no more protection fault errors!

Although, pressing the Escape key during the intro playing(played until the scrolling credits have rolled a few lines) does give me a black screen, instead of continuing on to the loading screen again for the second part.

**Comment by superfury** [comment]
With the even more recent bugfixes, it seems to run without problems, although slowly(still working on optimizing the emulator, demo running a 3MIPS 80386DX, in IPS cycle mode).

https://youtu.be/e_uzF5b8_UI
