### ISSUE TITLE
System unit volume setting is ignored

### ISSUE THREAD

**Issue by Magneticdud** [barotto/IBMulator#33]
Hi,  I'd like to disable the system fan noise while keeping the hdd and floppy noises.

I set system=0.1 and system=0.0 and it did not work, the noise is still high volume. I tried to delete the wav in share\sounds but it still plays

Am I doing something wrong?

**Comment by barotto** [comment]
Hi, yes I think you're doing something wrong, but I'm not sure what.
Assuming you're referring to the "realistic GUI mode" (system noises are not played in normal and compact modes), the [soundfx]:system value is working fine for me. Also deleting the wavs in the share/ibmulator/sounds/system folder should definitely mute the system.
Maybe you have different ibmulator versions and you're editing the wrong ini file?

**Comment by Magneticdud** [comment]
I'm running in compact mode

i changed the shader, but it was doing the sounds even in normal and default shader

i attach my ini. share\ibmulator\sounds\system\power_on.wav has been deleted

[ibmulator.ini.txt](https://github.com/barotto/IBMulator/files/2277220/ibmulator.ini.txt)

(btw great idea, the sounds add a lot of realism)

**Comment by barotto** [comment]
The hdd is much louder than the system fan.
Try to mute the hdd, you should hear nothing.
[soundfx]
hdd_spin=0

**Comment by Magneticdud** [comment]
right i confused system sound with hdd spin

thanks

**Comment by barotto** [comment]
Yeah, those rusty 80's HDDs are loud AF
