### ISSUE TITLE
Incorrect updating of PTE Dirty bit

### ISSUE THREAD

**Issue by barotto** [barotto/IBMulator#34]
The Dirty bit of a PTE is not properly set on a write memory operation when the same page has been previously accessed by a read operation.
So after the Accessed bit as been set on the first TLB miss, the Dirty bit will not be set on a subsequent write on the same page.

**Comment by superfury** [comment]
Well, that's simple: just don't include certain combinations of the r/w and accessed bits in the lookup operation. That's the way I do it in UniPCemu(to be more exact: it depends. Accessed is only included on writes during lookup. Writing anything into the TLB simply ignores the r/w and accessed bits in the tag, instead overwriting an entry's tag. Then it's simply a matter of making memory reads ignore the tag's accessed and r/w bits in the tag, while writes require them to both be set. If the (filtered) tag isn't found, perform a pagetable walk. If it's found, then it's contents is used for translation.
That way you remove duplicate tags for the same addresses, while reads take any combination of r/w and accessed. But writes force a pagetable walk.).

See my emulator's TLB/Paging unit: https://bitbucket.org/superfury/unipcemu/src/de86fe4e56e965056d0e429b818e188b41bdeb54/UniPCemu/cpu/paging.c?at=master
