### ISSUE TITLE
Incorrect memory segment limit checking

### ISSUE THREAD

**Issue by barotto** [barotto/IBMulator#35]
A #GP is not thrown when a memory access segment check is performed and:
  - the memory address is 0xffffffff
  - the segment limit is below 0xffffffff

**Comment by superfury** [comment]
UniPCemu handles limits in a simple way: any access that's past the limit(or reversed with top-down descriptors) will AND the validity(1 being valid) with a combination of the case whether or not it's past the address width.

In UniPCemu's case, it uses some simple precalcs that are loaded whenever a segment descriptor is loaded:
`void CPU_calcSegmentPrecalcs(SEGMENT_DESCRIPTOR *descriptor)
{
	word n;
	//Calculate the precalculations for execution for this descriptor!
	checkrights_cond *rights;
	uint_32 limits[2]; //What limit to apply?
	limits[0] = ((SEGDESCPTR_NONCALLGATE_LIMIT_HIGH(descriptor) << 16) | descriptor->desc.limit_low); //Base limit!
	limits[1] = ((limits[0] << 12) | 0xFFF); //4KB for a limit of 4GB, fill lower 12 bits with 1!
	descriptor->PRECALCS.limit = limits[SEGDESCPTR_GRANULARITY(descriptor)]; //Use the appropriate granularity to produce the limit!
	descriptor->PRECALCS.topdown = ((descriptor->desc.AccessRights & 0x1C) == 0x14); //Topdown segment?
	descriptor->PRECALCS.roof = (0xFFFF | (0xFFFF << (SEGDESCPTR_NONCALLGATE_D_B(descriptor) << 4))); //The roof of the descriptor!
	descriptor->PRECALCS.base = ((descriptor->desc.base_high << 24) | (descriptor->desc.base_mid << 16) | descriptor->desc.base_low); //Update the base address!
	rights = &checkrights_conditions[(descriptor->desc.AccessRights & 0xE)]; //What type do we check for(take it all, except the dirty bit)!
	for (n = 0; n < 0x100; ++n) //Calculate all conditions that error out or not!
	{
		descriptor->PRECALCS.rwe_errorout[n] = (((((n&rights->mask) == rights->comparision) == (rights->nonequals == 0)))&1); //Are we to error out on this condition?
	}
}

And the processing of it is:
`OPTINLINE byte verifyLimit(SEGMENT_DESCRIPTOR *descriptor, uint_64 offset)
{
	//Execute address test?
	INLINEREGISTER byte isvalid,topdown;
	topdown = descriptor->PRECALCS.topdown; //Are we a top-down segment?
	isvalid = (offset<=(uint_64)descriptor->PRECALCS.limit); //Valid address range!
	isvalid ^= topdown; //Apply expand-down data segment, if required, which reverses valid!
	isvalid &= (((offset>descriptor->PRECALCS.roof) & topdown)^1); //Limit to 16-bit/32-bit address space using topdown descriptors!
	isvalid &= 1; //Only 1-bit testing!
	return isvalid; //Are we valid?
}

The result of verifylimit is 1 when it's valid. When it returns 0, throw a #GP(for code and non-SS segment registers) or #SS(for stacks) fault, depending on the segment register used.
