### ISSUE TITLE
Running Windows 3.1 Emulator Crashes.

### ISSUE THREAD

**Issue by davek1959** [barotto/IBMulator#37]
IB V0.9 beta 1 on windows 7 pro 64bti, PS/1 Mode 2121, Installed no errors, Boot up looks normal until it tries to load windows 3.1, "app has requested the run time to terminate in an unusual way" then the emulator crashes. Help would be appreciated.

**Comment by barotto** [comment]
Can you run the program with the `-v 2` command line option and post the content of the log file here? Thank you.

**Comment by davek1959** [comment]
Thanks The solution to my problem was when I updated MS++ runtime and directx. Now it boots ok.
