### ISSUE TITLE
Using Windows, I keep my disk images on the D: and can't seem to manually navigate to that drive, from the floppy file explorer. 

### ISSUE THREAD

**Issue by misterspock1** [barotto/IBMulator#46]

**Comment by barotto** [comment]
I guess this is the combination of the file explorer being too primitive and Windows having multiple drives under different letters, which is a remnant of the old DOS legacy...

I suggest you to put the full path of your disk images directory in the `media_dir` ini file setting, under the `[program]` section, like

```
[program]
media_dir=D:\full\path\to\images
```
