### ISSUE TITLE
Can't assign Extended memory above 512K

### ISSUE THREAD

**Issue by kyousif87** [barotto/IBMulator#51]
Tried putting 2M, 4M, 6M, 8M and 16M in the ini file under [memory] section.
IBM PS/2 doesn't recognize them and only uses the base 2M of RAM

**Comment by barotto** [comment]
I can't reproduce the problem. It works as expected for me.

Please check the syntax. The program is a bit picky, it must be in the expected form otherwise it wont work, eg.:
```
[memory]
expansion=2M
```
Check the `log.txt` file and see if there's any errors reported.

**Comment by kyousif87** [comment]
My sincerest apologies.

So embarrassing, by mistake I didn't notice that it has to be M, not MB.

Thanks, keep up the great work! :)
