### ISSUE TITLE
Undocumented feature: Joystick support

### ISSUE THREAD

**Issue by kyousif87** [barotto/IBMulator#53]
While looking at the log file to debug a rather unrelated issue, I found this line:

> [INF0] gui | Joystick 0: Xbox 360 Controller (6 axes, 11 buttons)

I was surprised because I could not find anything in the documentation that mentions supporting joysticks. And indeed, I have an Xbox 360 hooked up to my computer which IBMulator detected it.

So I decided to see if it actually works. Loaded up the good old Prince of Persia, and lo and behold! It works :)
It's a bit difficult though, at least for me, to control the Prince using the analogue stick. It would be great if there is a way to map buttons on the gamepad.

**Comment by barotto** [comment]
Joystick support is undocumented as it's not tested and, as you discovered, it's not possible to remap controls.
This is one of the many features I'd like to properly implement some day...

**Comment by kyousif87** [comment]
Regardless, I was so happy that it worked :)
I am thinking to get a classic PC gamepad or joystick to try it out.
Thank you for all the efforts you are spending on this!

**Comment by barotto** [comment]
Implemented a remapping feature. Not super advanced but serviceable.

**Comment by kyousif87** [comment]
Thanks!
Love the new features, will test the new version ASAP :)
