### ISSUE TITLE
Problems with defining custom hard drive.

### ISSUE THREAD

**Issue by misterspock1** [barotto/IBMulator#54]
Can't figure out what I'm doing wrong. I created an image with CHS 1024/16/62 edited the ini file with the information, named the file hdd-type47.img, even tried placing it in the zip file with the other hard drive images... 

Log file says this: Creating new image file 'D:\IBM\PS1\hdd-type47.img'
[ERR0] hdd | Unable to create the image file
[ERR0] prg | exception caught during initialization! giving up :(
[INF0] prg | Program stop  

ini section:
type=47
path=D:\IBM\PS1\hdd-type47.img
readonly=no
save=yes
cylinders=1024
heads=16
sectors=62
seek_max=auto
seek_trk=auto
rot_speed=auto
interleave=auto

Also tried using the term: type=custom

**Comment by barotto** [comment]
Your ini file seems correct.

The `Unable to create the image file` message means that IBMulator has encoutered a problem while trying to physically create the `hdd-type47.img` file on drive D.

This is a file system error. It happens using `std::ofstream` to create the file or while trying to write to it. At this point no other info are available. Maybe a problem with directory/file permissions? Not enough space left?

Try to create the image in the user directory, removing the `D:\IBM\PS1\` part. See if that works. Then try to move the image in `D:\IBM\PS1\` and see if it can be used.

**Comment by misterspock1** [comment]
After receiving your response I realized I mistyped the directory name! Fixed and all is working well, now! Thank you!

**Comment by barotto** [comment]
Thank you for your feedback. This is actually an error condition that can be detected during init. I'll try to improve the error messages.
