### ISSUE TITLE
Control-Alt-Delete

### ISSUE THREAD

**Issue by misterspock1** [barotto/IBMulator#55]
How do you define or simulate a Control-Alt-Delete in the emulator? Didn't see this anywhere, 

                                 Thanks

**Comment by barotto** [comment]
As stated in the README:

* CTRL+DEL: send CTRL+ALT+DEL to the guest OS
* CTRL+INS: send SysRq to the guest OS
* CTRL+END: send Break to the guest OS

These combinations cannot be remapped, yet (planned feature).

**Comment by misterspock1** [comment]
Thanks, I must have missed it, I thought I read the whole thing...
