### ISSUE TITLE
Alt-Tab emulation

### ISSUE THREAD

**Issue by vinriviere** [barotto/IBMulator#56]
First of all, hats off for this great emulator! Very intuitive to use. I just love the sounds.

My question:
When running IBMulator on Windows, is it possible to simulate Alt-Tab inside the emulator? Because when I run i.e. Windows 3.0 and I press Alt-Tab, that keystroke is handled by the Windows host, not the emulator.

**Comment by barotto** [comment]
I'm afraid it's not possible rn. (I didn't even know alt-tab was a valid combination in Win 3.0 so it didn't occurred to me to implement it in the emulator...)
Thank you for pointing it out though, I'll add this combination to the next version.
Or maybe I'll finally implement a proper key mapper!

**Comment by vinriviere** [comment]
Thanks! For sure Alt-Tab was used by Windows 3.1. That's a key feature to switch between different MS-DOS tasks. I'm not sure about Windows 3.0, this is why I wanted to try. Another one, very useful, is Alt+Enter to switch MS-DOS sessions between fullscreen and windowed. Unfortunately it is not usable in the emulator, for same reasons.
