### ISSUE TITLE
Softice, 386 debug register, and copy protected disk

### ISSUE THREAD

**Issue by danrevella** [barotto/IBMulator#64]
Please IBMulator is able in running Softice x dos who have to access 386 debug register?
Also, is there support for floppy games copy-protected?
Thanks

**Comment by barotto** [comment]
I've briefly tried SoftICE 2.8 under DOS 6 and it appeared to work, but 386 debug registers are largely untested and I'm not sure if they work as intended.
Some feedback on this is very much appreciated!

Currently the only disk format supported for images is raw sector (img/ima) so there's no low level emulation for copy protected disks.
I was looking recently on this issue and found this lib https://github.com/keirf/Disk-Utilities which might help to add support, though I have no experience on the matter of copy protection...
