### ISSUE TITLE
Emulator crash with "Unhandled write to port 0x0096" error executing the IBM PS1 2121 Advanced Diagnostics

### ISSUE THREAD

**Issue by MX9000** [barotto/IBMulator#71]
I tried to start the emulator (0.15) with the floppy image "IBM PS1 2121 - Advanced Diagnostics.img" but when I select the option "0 - SYSTEM CHECKOUT" the emulator closes shortly after displaying the message "PROGRAMS LOADING - PLEASE WAIT".
I configured the emulator with the BIOS "IBM PS1 2121 - ROM.zip" and the hard disk image "IBM PS1 2121 - HDD image with Windows 3.0 (US).zip"
I attach the log where the error in question appears:
[log.txt](https://github.com/barotto/IBMulator/files/9893317/log.txt)
Thank you very much!

**Comment by barotto** [comment]
Port 0x96 is Adapter Enable/Setup Register.
The crash is caused by an exit(1) call in systemboard.cpp line 186 that shouldn't be there. But even if replaced with a simple warning, the advanced diagnostics program won't probably work because POS registers are not fully implemented yet.

**Comment by MX9000** [comment]
Many thanks for your technical explanation.
I will try again in the next releases: IBMulator is really fun!
Good job!
