### ISSUE TITLE
CD Rom Add-on? Real or Virtual?

### ISSUE THREAD

**Issue by blairc64** [barotto/IBMulator#79]
Is there any way to mount a real CD-Rom (Hopefully via my Apple Superdrive)?

I had the CD-Rom add on back in the day... and actually still have the CD-Rom Games. :) I would love to be able to play them using this version of my PS/1.

I'm not seeing any way to really do this in the config file.
I'm also not seeing any references to CD-Rom in the docs.

I must be missing something.
If not, is there any reason at least ISO/img mounting could be added?

**Comment by barotto** [comment]
Thanks for using IBMulator. There's no support for CD-ROMs at this moment, mostly for lack of time and interest, tho it might be added in the future, in the form of virtual iso file based ATAPI drives.

**Comment by barotto** [comment]
CD-ROM emulation added in v0.18
