### ISSUE TITLE
Error Launching on Windows with Intel GPUs: illegal characters in slang shaders

### ISSUE THREAD

**Issue by VeoXXX** [barotto/IBMulator#87]
Error Launching on Windows 10 due to `Error Compiling Shader"crt.slang"`
Log.txt filled with `[ERR0] gui |   ERROR: 7:1: '' :  illegal character (") (0x22)`
I seems to be too stupid

**Comment by barotto** [comment]
What's the model of your video card?
Can you attach the Log.txt file here?

**Comment by VeoXXX** [comment]
`[INF0] ogl | Loading shader preset 'F:\IBMulator\IBMulator\share\ibmulator\shaders\realistic_mode\stock.slangp' ...
[ERR0] gui | Error compiling shader 'F:\IBMulator\IBMulator\share\ibmulator\shaders\ps1\crt.slang'
[ERR0] gui |   ERROR: 6:1: '' :  illegal character (") (0x22)
last message repeated 1 more times
[ERR0] gui |   ERROR: 7:1: '' :  illegal character (") (0x22)
last message repeated 1 more times
[ERR0] gui |   ERROR: 8:1: '' :  illegal character (") (0x22)
last message repeated 1 more times
[ERR0] gui |   ERROR: 9:1: '' :  illegal character (") (0x22)
last message repeated 1 more times
[ERR0] gui |   ERROR: 10:1: '' :  illegal character (") (0x22)
last message repeated 1 more times
[ERR0] gui |  Source:
[ERR0] gui |   1: #version 330 core
[ERR0] gui |   2: #define IBMU_PASS_NUMBER 0
[ERR0] gui |   3: #define VGA_REFLECTION 0
[ERR0] gui |   4: #define CRT_SCALE 1.0
[ERR0] gui |   5: #define BRT_TINT vec3(1.0,1.0,1.5)
[ERR0] gui |   6: 
[ERR0] gui |   7: #pragma parameter vgaScale "VGA image scale" 0.85 0.1 1.0 0.01
[ERR0] gui |   8: #pragma parameter vgaConvergence "VGA Convergence" 0.5 0.0 1.0 0.1
[ERR0] gui |   9: #pragma parameter crtCurvature "CRT Curve Radius" 8.0 0.0 10.0 0.1
[ERR0] gui |   10: #pragma parameter crtEnvMapEnabled "CRT Environment map enabled" 1.0 0.0 1.0 1.0
[ERR0] gui |   11: #pragma parameter ambientFromCRT "Max. ambient light from the CRT" 0.1 0.0 1.0 0.05
[ERR0] gui |   12: 
[ERR0] gui |   13: 
[ERR0] gui |   14: layout(std140) uniform Globals
[ERR0] gui |   15: {
[ERR0] gui |   16: mat4  MVP;
[ERR0] gui |   17: vec4  OutputSize;
[ERR0] gui |   18: float ibmu_Brightness;
[ERR0] gui |   19: float ibmu_Contrast;
[ERR0] gui |   20: float ibmu_Saturation;
[ERR0] gui |   21: float ibmu_Ambient;
[ERR0] gui |   22: int   ibmu_Monochrome;
[ERR0] gui |   23: int   ibmu_PowerOn;
[ERR0] gui |   24: } globals;
[ERR0] gui |   25: 
[ERR0] gui |   26: layout(std140) uniform Params
[ERR0] gui |   27: {
[ERR0] gui |   28: float vgaConvergence;
[ERR0] gui |   29: float vgaScale;
[ERR0] gui |   30: float crtCurvature;
[ERR0] gui |   31: float crtEnvMapEnabled;
[ERR0] gui |   32: float ambientFromCRT;
[ERR0] gui |   33: } params;
[ERR0] gui |   34: 
[ERR0] gui |   35: 
[ERR0] gui |   36: #pragma stage vertex
[ERR0] gui |   37: 
[ERR0] gui |   38: layout(location=0) in vec4 Position;
[ERR0] gui |   39: layout(location=1) in vec2 TexCoord;
[ERR0] gui |   40: out vec2 vTexCoord;
[ERR0] gui |   41: 
[ERR0] gui |   42: void main()
[ERR0] gui |   43: {
[ERR0] gui |   44: gl_Position = globals.MVP * Position;
[ERR0] gui |   45: vTexCoord = TexCoord.xy;
[ERR0] gui |   46: }
[ERR0] gui |   47: 
[ERR0] gui |   48: 
[ERR0] prg | ERROR: 6:1: '' :  illegal character (") (0x22)
ERROR: 6:1: '' :  illegal character (") (0x22)
ERROR: 7:1: '' :  illegal character (") (0x22)
ERROR: 7:1: '' :  illegal character (") (0x22)
ERROR: 8:1: '' :  illegal character (") (0x22)
ERROR: 8:1: '' :  illegal character (") (0x22)
ERROR: 9:1: '' :  illegal character (") (0x22)
ERROR: 9:1: '' :  illegal character (") (0x22)
ERROR: 10:1: '' :  illegal character (") (0x22)
ERROR: 10:1: '' :  illegal character (") (0x22)
`
My Graphic Chip is Intel HD Graphics 5500

**Comment by barotto** [comment]
Can you please try this version and tell me if it works? 
https://drive.google.com/file/d/1LrEwtY62_vV1xG77v2JK2gufRF3r7TFL/view?usp=drive_link

**Comment by VeoXXX** [comment]
> Can you please try this version and tell me if it works? https://drive.google.com/file/d/1LrEwtY62_vV1xG77v2JK2gufRF3r7TFL/view?usp=drive_link

Sorry but I'm in China, I can't use google at least now...
Your emulator works fine(with normal GUI), thanks for your great job :-)

**Comment by VeoXXX** [comment]
[crt.zip](https://github.com/barotto/IBMulator/files/15443252/crt.zip)

**Comment by barotto** [comment]
Sorry I had to put the file on google because GitHub has a 25MB file size limit.

Does this link work for you?
https://www.mediafire.com/file/54xn9lx0wudysa5/ibmulator-unstable-g2ca7f10-dirty-windows.x86_64.zip/file

**Comment by VeoXXX** [comment]
Worked Out Great, same as the new emulator.
Thanks for your support!
